RGBLIGHT_ENABLE    = no

MOUSEKEY_ENABLE    = no
NKRO_ENABLE        = yes
OLED_ENABLE        = yes
OLED_DRIVER        = SSD1306
LTO_ENABLE         = yes

RGB_MATRIX_ENABLE  = yes
RGB_MATRIX_DRIVER  = WS2812
OLED_DRIVER_ENABLE = yes
EXTRAKEY_ENABLE = yes 
TAP_DANCE_ENABLE = yes
